batchDeployment:
  batch:
    image:
      repository: jinmanpark/spring-cloud-msa-batch-service
      tag: '3'
  replicas: 1
batchService:
  ports:
    - port: 8020
      targetPort: 8020
  type: ClusterIP
businessDeployment:
  business:
    image:
      repository: jinmanpark/spring-cloud-msa-business-service
      tag: '1'
  replicas: 1
businessService:
  ports:
    - port: 8030
      targetPort: 8030
  type: ClusterIP
discoveryDeployment:
  discovery:
    image:
      repository: jinmanpark/spring-cloud-msa-discovery-service
      tag: '2'
  replicas: 1
discoveryService:
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
gatewayDeployment:
  gateway:
    image:
      repository: jinmanpark/spring-cloud-msa-gateway-service
      tag: '2'
  replicas: 1
gatewayService:
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
postgres:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
  externalIPs: 10.10.50.232
postgresDeployment:
  postgres:
    image:
      repository: jinmanpark/spring-cloud-msa-postgres
      tag: v20240405
  replicas: 1
pvc:
  msaPostgresPvc:
    storageClass: rook-ceph-block
    storageRequest: 10Gi
userDeployment:
  replicas: 1
  user:
    image:
      repository: jinmanpark/spring-cloud-msa-user-service
      tag: '2'
userService:
  ports:
    - port: 8010
      targetPort: 8010
  type: ClusterIP
deployment:
  discovery:
    image:
      tag: '2'
