apiVersion: v1
kind: Service
metadata:
  name: batch-service
  labels:
  {{- include "woodpecker-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.batchService.type }}
  selector:
    app: woodpecker-batch
  {{- include "woodpecker-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.batchService.ports | toYaml | nindent 2 -}}
