apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msa-helm.fullname" . }}-batch-deployment
  labels:
    app: msa-batch
  {{- include "msa-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.batchDeployment.replicas }}
  selector:
    matchLabels:
      app: msa-batch
    {{- include "msa-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: msa-batch
      {{- include "msa-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.batchDeployment.batch.image.repository }}:{{ .Values.batchDeployment.batch.image.tag
          | default .Chart.AppVersion }}
        name: batch
        ports:
        - containerPort: 8020
        resources: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msa-helm.fullname" . }}-business-deployment
  labels:
    app: msa-business
  {{- include "msa-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.businessDeployment.replicas }}
  selector:
    matchLabels:
      app: msa-business
    {{- include "msa-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: msa-business
      {{- include "msa-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.businessDeployment.business.image.repository }}:{{ .Values.businessDeployment.business.image.tag
          | default .Chart.AppVersion }}
        name: business
        ports:
        - containerPort: 8030
        resources: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msa-helm.fullname" . }}-discovery-deployment
  labels:
    app: msa-discovery
  {{- include "msa-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.discoveryDeployment.replicas }}
  selector:
    matchLabels:
      app: msa-discovery
    {{- include "msa-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: msa-discovery
      {{- include "msa-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        - name: eureka.environment
          value: prod
        image: {{ .Values.discoveryDeployment.discovery.image.repository }}:{{ .Values.discoveryDeployment.discovery.image.tag
          | default .Chart.AppVersion }}
        name: discovery
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msa-helm.fullname" . }}-gateway-deployment
  labels:
    app: msa-gateway
  {{- include "msa-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gatewayDeployment.replicas }}
  selector:
    matchLabels:
      app: msa-gateway
    {{- include "msa-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: msa-gateway
      {{- include "msa-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.gatewayDeployment.gateway.image.repository }}:{{ .Values.gatewayDeployment.gateway.image.tag
          | default .Chart.AppVersion }}
        name: gateway
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msa-helm.fullname" . }}-postgres-deployment
  labels:
    app: msa-postgres
  {{- include "msa-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresDeployment.replicas }}
  selector:
    matchLabels:
      app: msa-postgres
    {{- include "msa-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: msa-postgres
      {{- include "msa-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.postgresDeployment.postgres.image.repository }}:{{ .Values.postgresDeployment.postgres.image.tag
          | default .Chart.AppVersion }}
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        envFrom:
          - secretRef:
              name: postgres-secret
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /mnt/postgresql-data
            name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: msa-postgres-pvc
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msa-helm.fullname" . }}-user-deployment
  labels:
    app: msa-user
  {{- include "msa-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.userDeployment.replicas }}
  selector:
    matchLabels:
      app: msa-user
    {{- include "msa-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: msa-user
      {{- include "msa-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.userDeployment.user.image.repository }}:{{ .Values.userDeployment.user.image.tag
          | default .Chart.AppVersion }}
        name: user
        ports:
        - containerPort: 8010
        resources: {}
      restartPolicy: Always
