apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-helm.fullname" . }}-batch-deployment
  labels:
    app: woodpecker-batch
  {{- include "spring-cloud-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.batchDeployment.replicas }}
  selector:
    matchLabels:
      app: woodpecker-batch
    {{- include "spring-cloud-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: woodpecker-batch
      {{- include "spring-cloud-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.batchDeployment.batch.image.repository }}:{{ .Values.batchDeployment.batch.image.tag
          | default .Chart.AppVersion }}
        name: batch
        ports:
        - containerPort: 8020
        resources: {}
      nodeSelector:
        woodpecker-node: "true"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-helm.fullname" . }}-business-deployment
  labels:
    app: woodpecker-business
  {{- include "spring-cloud-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.businessDeployment.replicas }}
  selector:
    matchLabels:
      app: woodpecker-business
    {{- include "spring-cloud-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: woodpecker-business
      {{- include "spring-cloud-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.businessDeployment.business.image.repository }}:{{ .Values.businessDeployment.business.image.tag
          | default .Chart.AppVersion }}
        name: business
        ports:
        - containerPort: 8040
        resources: {}
      nodeSelector:
        woodpecker-node: "true"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-helm.fullname" . }}-discovery-deployment
  labels:
    app: woodpecker-discovery
  {{- include "spring-cloud-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.discoveryDeployment.replicas }}
  selector:
    matchLabels:
      app: woodpecker-discovery
    {{- include "spring-cloud-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: woodpecker-discovery
      {{- include "spring-cloud-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        - name: eureka.environment
          value: prod
        image: {{ .Values.discoveryDeployment.discovery.image.repository }}:{{ .Values.discoveryDeployment.discovery.image.tag
          | default .Chart.AppVersion }}
        name: discovery
        ports:
        - containerPort: 8761
        resources: {}
      nodeSelector:
        woodpecker-node: "true"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-helm.fullname" . }}-gateway-deployment
  labels:
    app: woodpecker-gateway
  {{- include "spring-cloud-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gatewayDeployment.replicas }}
  selector:
    matchLabels:
      app: woodpecker-gateway
    {{- include "spring-cloud-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: woodpecker-gateway
      {{- include "spring-cloud-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.gatewayDeployment.gateway.image.repository }}:{{ .Values.gatewayDeployment.gateway.image.tag
          | default .Chart.AppVersion }}
        name: gateway
        ports:
        - containerPort: 9000
        resources: {}
      nodeSelector:
        woodpecker-node: "true"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-helm.fullname" . }}-postgres-deployment
  labels:
    app: woodpecker-postgres
  {{- include "spring-cloud-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresDeployment.replicas }}
  selector:
    matchLabels:
      app: woodpecker-postgres
    {{- include "spring-cloud-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: woodpecker-postgres
      {{- include "spring-cloud-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.postgresDeployment.postgres.image.repository }}:{{ .Values.postgresDeployment.postgres.image.tag
          | default .Chart.AppVersion }}
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
      nodeSelector:
        woodpecker-node: "true"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-helm.fullname" . }}-user-deployment
  labels:
    app: woodpecker-user
  {{- include "spring-cloud-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.userDeployment.replicas }}
  selector:
    matchLabels:
      app: woodpecker-user
    {{- include "spring-cloud-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: woodpecker-user
      {{- include "spring-cloud-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: prod
        image: {{ .Values.userDeployment.user.image.repository }}:{{ .Values.userDeployment.user.image.tag
          | default .Chart.AppVersion }}
        name: user
        ports:
        - containerPort: 8010
        resources: {}
      nodeSelector:
        woodpecker-node: "true"
      restartPolicy: Always
