apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: woodpecker-ns
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /discovery
            pathType: Prefix
            backend:
              service:
                name: discovery-service
                port:
                  number: 8761
          - path: /gateway
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 9000
          # web-service framework 추가 예정
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 3000
