apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
  {{- include "woodpecker-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.userService.type }}
  selector:
    app: woodpecker-user
  {{- include "woodpecker-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.userService.ports | toYaml | nindent 2 -}}
