apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-postgres-pvc
  labels:
  {{- include "msa-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.woodpeckerPostgresPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.woodpeckerPostgresPvc.storageClass | quote }}
